nav:
  - Tracker: tracker
  - Status: status
  - Track: track
  - Geocoder: geocoder.md
  - Route: route
  - Zone: zone
  - Beacon: beacon
  - APN Settings: apn_settings.md
  - Map Layer: map_layer.md
  - Delivery: delivery.md
  - Retranslator: retranslator.md

