nav:
  - APN Settings: apn_settings.md
  - Group: group.md
  - Employee: employee.md
  - Chat: chat.md
  - Readings: readings.md
  - Counter: counter.md
  - Trusted Number: trusted_number.md
  - Contact: contact.md
  - Output: output.md
  - Engine Immobilizer: engine_immobilizer.md
  - Index: index.md
  - Led: led.md
  - Datalogger: datalogger.md
  - Alarm Mode: alarm_mode.md
  - Avatar: avatar.md
  - Retranslator: retranslator.md
  - Mobile: mobile.md
  - Settings: settings
  - Sensor: sensor
  - Rules: rules
  - Command: command
  - Stats: stats
