nav:
  - Base: base.md
  - User: user
  - Entities: entity
  - Data Import: data.md
  - Files: file.md
  - Notifications: notification.md
  - History: history
  - Report: report
  - Subusers: subuser
  - Timezone: timezone.md
  - Feedback: feedback.md
  - Dealer: dealer.md
  - API Keys: api-keys.md
  - Plugins: plugin
  - Tag: tag
