title: How To
nav:
  - index.md
  - Get hash of an API Key: 'get-api-key.md'
  - Register a device: 'how-to-register-a-device.md'
  - Get tracker list: 'get-tracker-list.md'
  - Get track points: 'get-track-points.md'
  - Get sensors and counters data: 'getting-measurements-and-counters-from-devices.md'
  - Virtual sensors usage: 'virtual-sensors.md'
  - Create geofences: 'how-to-create-geofences.md'
  - Points of interest (POI) usage: 'work-with-POIs.md'
  - Use rules: 'use-rules.md'
  - Work with notifications: 'how-to-work-with-notifications.md'
  - Getting push notifications: 'getting-pushes.md'
  - Work with tasks: 'how-to-work-with-tasks.md'
  - Forms usage: 'forms-creation.md'
  - Work with statuses: 'how-to-work-with-statuses.md'
  - Send commands to device: 'how-to-send-commands-to-device.md'
  - Obtain information from report: 'how-to-obtain-information-from-report.md'
  - Tags usage: 'tags-usage.md'
  - Vehicles and service works usage: 'service-works-exploitation.md'
  - Work with driver journals: 'driver-journals-usage.md'
  - Create check-ins via API: 'how-to-create-checkins-via-api.md'
  - Tracking stationary objects: 'tracking-stationary=objects.md'
