title: How To
nav:
    - how-to.md
    - get-session-hash.md
    - get-tracker-list.md
    - get-track-points.md
    - how-to-obtain-information-from-report.md
    - how-to-create-a-rule.md
    - how-to-work-with-notifications.md
    - how-to-send-commands-to-device.md
    - how-to-work-with-statuses.md
    - how-to-work-with-tasks.md
