#!/usr/bin/env python3
"""
Bulletproof count of Backend API paths documented under docs/user-api/backend-api/resources/.

Uses every path source we can reliably parse:
  1. Literal curl URLs: https://.../v2/...'
  2. Template curl URLs: {{ extra.api_example_url }}/...' or {{extra.api_example_url}}/...'

Outputs a canonical sorted list and count. Use the count as the target when updating
the OpenAPI spec (spec paths >= this count, with every path in the list present).

Usage:
  python scripts/extract_docs_endpoints.py           # extract, compare to OpenAPI, print report
  python scripts/extract_docs_endpoints.py --target   # print only canonical count and write target file
"""

import re
import json
import sys
from pathlib import Path

DOCS_DIR = Path(__file__).resolve().parent.parent / "docs" / "user-api" / "backend-api" / "resources"
OPENAPI_PATH = Path(__file__).resolve().parent.parent / "navixy-backend-api-openapi.json"
TARGET_FILE = Path(__file__).resolve().parent.parent / "docs" / "user-api" / "backend-api" / "BACKEND_API_PATH_TARGET.txt"

# Literal host: https://api.eu.navixy.com/v2/path' or https://api.navixy.com/v2/path'
PATTERN_LITERAL = re.compile(r"https?://[^/]+/v2/([a-z_/]+?)(?:\?|'|$)")
# Template: {{ extra.api_example_url }}/path' or {{extra.api_example_url}}/path
PATTERN_TEMPLATE = re.compile(r"\{\{\s*extra\.api_example_url\s*\}\}/([a-z_/]+?)(?:\?|'|$)", re.IGNORECASE)


def normalize_path(segment: str) -> str:
    """Return path with leading slash, no trailing slash."""
    segment = segment.strip("/")
    return "/" + segment if segment else "/"


def extract_from_docs() -> set[str]:
    paths = set()
    for md in DOCS_DIR.rglob("*.md"):
        text = md.read_text(encoding="utf-8", errors="ignore")
        for pattern in (PATTERN_LITERAL, PATTERN_TEMPLATE):
            for m in pattern.finditer(text):
                path = normalize_path(m.group(1))
                if path != "/":
                    paths.add(path)
    return paths


def main():
    docs_paths = extract_from_docs()
    canonical = sorted(docs_paths)
    target_count = len(canonical)

    if "--target" in sys.argv:
        # Only output target count and write canonical list to file
        TARGET_FILE.parent.mkdir(parents=True, exist_ok=True)
        TARGET_FILE.write_text(
            f"# Backend API path target (generated by scripts/extract_docs_endpoints.py)\n"
            f"# Total paths documented under docs/user-api/backend-api/resources/: {target_count}\n"
            f"# Use this count as the minimum when updating navixy-backend-api-openapi.json\n\n"
            + "\n".join(canonical) + "\n",
            encoding="utf-8",
        )
        print(f"BACKEND_API_PATH_TARGET={target_count}")
        print(f"Written {target_count} paths to {TARGET_FILE}")
        return

    # Full report: compare to OpenAPI
    with open(OPENAPI_PATH, encoding="utf-8") as f:
        spec = json.load(f)
    openapi_paths = set(spec["paths"].keys())

    only_docs = docs_paths - openapi_paths
    only_spec = openapi_paths - docs_paths

    print("=== Backend API path target (from docs)")
    print(f"    Canonical count: {target_count}")
    print(f"    OpenAPI paths:   {len(openapi_paths)}")
    print()
    print("=== In DOCS but NOT in OpenAPI (missing from spec):")
    for p in sorted(only_docs):
        print(p)
    if not only_docs:
        print("    (none)")
    print()
    print("=== In OpenAPI but NOT in docs (optional/canonical):")
    for p in sorted(only_spec)[:30]:
        print(p)
    if len(only_spec) > 30:
        print(f"    ... and {len(only_spec) - 30} more")
    print()
    print(f"=== Missing count: {len(only_docs)}")
    print(f"=== Target for spec: spec must have at least {target_count} paths and include every path in the canonical list.")


if __name__ == "__main__":
    main()
