title: Field service management
nav:
  - Manage tasks: manage-tasks.md
  - Creating forms for tasks: create-forms.md
  - Change task statuses: change-task-statuses.md
  - Optimizing routes: optimize-routes.md
  - Create check-ins: check-ins.md
